#TODO use Clojure config
version: 2
aliases:
  cache:
    lein_cache: &CACHE
      key: cache-{{ .Environment.CACHE_VERSION }}-{{ .Environment.NODE_VERSION }}-{{ checksum "project.clj" }}-{{ checksum "package-lock.json" }}
      paths:
      - ~/.lein
      - ~/.m2
      - node_modules
  containers:
    docker: &DEFAULT
    - image: jesiio/build-bus:latest
      environment:
        JVM_OPTS: -Xmx3200m
        DEBUG: 1
  commands:
    cancel_redundant: &CANCEL_REDUNDANT
      run:
        name: Check & Cancel Redundant Build
        command: 'cancel-redundant-builds.sh'
    submodule: &SUBMODULE
      run: git submodule update --init --recursive
jobs:
  deps:
    docker: *DEFAULT
    steps:
    - *CANCEL_REDUNDANT
    - checkout
    - *SUBMODULE
    - restore_cache:
        <<: *CACHE
    - run: './clojure-polyline.sh deps'
    - save_cache:
        <<: *CACHE
  test_clj:
    docker: *DEFAULT
    steps:
    - *CANCEL_REDUNDANT
    - checkout
    - *SUBMODULE
    - restore_cache:
        <<: *CACHE
    - run: './clojure-polyline.sh test'
    - save_cache:
        <<: *CACHE
  test_cljs:
    docker: *DEFAULT
    steps:
    - *CANCEL_REDUNDANT
    - checkout
    - *SUBMODULE
    - restore_cache:
        <<: *CACHE
    - run: './clojure-polyline.sh test-cljs'
    - save_cache:
        <<: *CACHE
  snapshot:
    docker: *DEFAULT
    steps:
    - *CANCEL_REDUNDANT
    - checkout
    - *SUBMODULE
    - restore_cache:
        <<: *CACHE
    - run: './clojure-polyline.sh snapshot'
    - save_cache:
        <<: *CACHE
  release:
    docker: *DEFAULT
    steps:
    - *CANCEL_REDUNDANT
    - checkout
    - *SUBMODULE
    - restore_cache:
        <<: *CACHE
    - run: './clojure-polyline.sh release'
    - save_cache:
        <<: *CACHE
workflows:
  version: 2
  build:
    jobs:
    - deps
    - test_clj:
        requires:
        - deps
    - test_cljs:
        requires:
        - deps
    - snapshot:
        context: JESI
        requires:
        - test_clj
        - test_cljs
        filters:
          branches:
            ignore: /^(master|develop)$/
    - release:
        context: JESI
        requires:
        - test_clj
        - test_cljs
        filters:
          branches:
            only: master
